FRAMEWORK_VERSION = "1.0.0"
SCHEMA_PREFIX = "org-agent-mesh"
AUTHORITY_TIERS = ("ORCHESTRATOR", "REVIEWER", "SPECIALIST")
EVIDENCE_CLASSES = (
    "AUTHORITATIVE_SOURCE", "DIRECT_OBSERVATION", "ANALYSIS", "MODEL_OR_SIMULATION",
    "AUTOMATED_VALIDATION", "HUMAN_VALIDATION", "OPERATIONAL_VALIDATION", "EXTERNAL_EVIDENCE"
)
PRESENCE_STATES = ("ACTIVE", "IDLE", "BLOCKED", "LATE", "RELEASED", "FAILED", "UNKNOWN")
REVIEW_DISPOSITIONS = ("READY_FOR_INTEGRATION", "NEEDS_MORE_EVIDENCE", "REJECTED", "SUPERSEDED", "BLOCKED")
CAPABILITIES = (
    "READ_SOURCE", "WRITE_WORKING_ARTIFACTS", "WRITE_ACCEPTED_STATE", "SEND_EXTERNAL_COMMUNICATION",
    "MODIFY_EXTERNAL_SYSTEM", "DELETE_DATA", "ACCESS_SENSITIVE_DATA", "APPROVE_RELEASE",
    "AUTHORIZE_FINANCIAL_ACTION", "AUTHORIZE_POLICY_CHANGE"
)
MESSAGE_KINDS = (
    "CLAIM", "FINDING", "BLOCKER", "REQUEST", "REVIEW_REQUEST", "REVIEW_DISPOSITION",
    "CONTRADICTION", "HANDOFF", "DECISION", "SUPERSESSION", "SERVICE_CHECKPOINT", "RELEASE_CLOSE"
)
UNKNOWN_STATES = ("UNKNOWN", "ASSUMED", "REQUIRES_HUMAN", "REQUIRES_EXTERNAL_EVIDENCE")
